import turtle

turtle.bgcolor('blue')
s=turtle.Turtle()

def curve(value):
    for i in range(value): 
        s.right(1) 
        s.forward(1)
        
s.speed(1)
s.penup() 
s.goto(0,43) 
s.pendown() 
s.begin_fill() 
s.color('black','red')
s.pensize(3) 
s.forward(81.5)
s.right(49.4) 
s.forward(58) 
s.right(81.42) 
s.forward(182) 
s.right(98.36) 
s.forward(182) 
s.right(81.42) 
s.forward(58) 
s.right(49.4) 
s.forward(81.5) 
s.end_fill() 
s.penup() 

s.goto(38,32) 
s.pendown() 
s.begin_fill()  
s.color('black','gold')
s.forward(13)
s.right(120) 
s.forward(13) 
s.right(120) 
s.forward(13) 
s.end_fill()
s.penup() 

s.goto(81.5,25)
s.pendown() 
s.begin_fill() 
s.right(210) 
s.forward(25) 
s.right(90) 
s.forward(38) 
s.right(45) 
s.circle(82,90)
s.left(90) 
s.circle(82,60) 
curve(61) # вызвать функцию кривой
s.left(90) 
s.forward(57) 
s.left(90) 
s.forward(32) 
s.end_fill() 
s.penup() 
s.home()

s.goto(-69,-38)
s.pendown()
s.begin_fill()
curve(20)# вызвать функцию кривой
s.forward(33)
s.left(10)
s.circle(82,20)
curve(30)# вызвать функцию кривой
s.forward(10)
s.right(110)
curve(40)# вызвать функцию кривой
s.right(10)
s.circle(50,10)
curve(45)# вызвать функцию кривой
s.right(5)
s.forward(45)
s.end_fill()
s.penup()
s.home()

s.goto(20,-100)
s.pendown()
s.begin_fill()
s.right(135)
s.forward(27)
s.right(90)
s.forward(27)
s.right(135)
s.forward(38.18)
s.end_fill()
s.penup()
s.home()
 
s.goto(-57,32)
s.pendown()
s.begin_fill()
s.right(180)
s.forward(18)
s.left(45)
s.forward(44)
s.left(80)
s.forward(15)
s.left(130)
curve(40)# вызвать функцию кривой
s.forward(20)
s.end_fill()
 
s.hideturtle() 
turtle.exitonclick()

